const DEV_EXPRESS_PORT = 9000;
const SUCCESS_CODE = 200;
const NOT_FOUND_ERROR_CODE = 404;
const NOT_FOUND_ERROR_MESSAGE = "Route not found";
const SERVER_INTERNAL_ERROR_CODE = 500;
const SERVER_INTERNAL_ERROR_MESSAGE = "Server internal error";
const CRYPTO_NOT_RECOGNIZED_ERROR_CODE = 204;
const CRYPTO_NOT_RECOGNIZED_ERROR_MESSAGE = "Could not find coin with the given id";
const BAD_REQUEST_ERROR_CODE = 400;
const BAD_REQUEST_ERROR_MESSAGE = "Bad request"

module.exports = {
    DEV_EXPRESS_PORT,
    SUCCESS_CODE,
    NOT_FOUND_ERROR_CODE,
    NOT_FOUND_ERROR_MESSAGE, 
    SERVER_INTERNAL_ERROR_CODE,
    SERVER_INTERNAL_ERROR_MESSAGE,
    CRYPTO_NOT_RECOGNIZED_ERROR_CODE,
    CRYPTO_NOT_RECOGNIZED_ERROR_MESSAGE,
    BAD_REQUEST_ERROR_CODE,
    BAD_REQUEST_ERROR_MESSAGE
}
    